wiki/wiki/encyclopedia/urls.py
from django.urls import path

from . import views


app_name= "entries"
 
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

wiki/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

wiki/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/wiki/encyclopedia/views.py
from django.shortcuts import render

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def add(request):
    return render(request, "encyclopedia/add.html")

wiki/wiki/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Add Entries</h1>

    <form action="">
        <input type="text " name="entry">
        <input type="submit">
    </form>
    <a href = "{% url 'entries:index' %}" > View Entries</a>
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>{{ entry }}</li>
        {% endfor %}
    </ul>

<a href="{% url 'entries:add' %}">Add a New Entry</a>
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form>
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'entries:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'entries:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'entries:index' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>